### PR TITLE
Tests for PR #75

### PR DESCRIPTION
**Pull request by jibran**

### CODE REVIEW

**Comment by jibran** [comment]
Over to you @LionsAd. I don't know a lot about this fail. Feel free to fix it or won't fix it.

**Comment by LionsAd** [comment]
I think it was just a test fluke.

**Comment by jibran** [comment]
test this please.

**Comment by LionsAd** [comment]
Hm, not yet working. No real idea why, will debug more later.

**Comment by LionsAd** [comment]
Tests pass now!

**Pull request merged**
