### PR TITLE
Switch to drush 8.0.* because drush 8.1.0 has some problems with runserver.

### PR DESCRIPTION
**Pull request by dsnopek**
This is to work around this issue in drush 8.1.0:

https://github.com/drush-ops/drush/issues/2157

### CODE REVIEW

**Comment by LionsAd** [comment]
@dsnopek Merged, thanks. Would you like to become co-maintainer of drupal_ti?

I trust you a lot and unfortunately I don't have the time to dedicate to this at this moment that I wish I had.

Obviously it would be no obligation to do anything, just in case you wanted to merge things like this yourself. So more collaboration access instead of co-maintainer - unless you wanted to.

Thanks,

Fabian

**Comment by dsnopek** [comment]
Sure, thanks! I don't necessarily have a ton of time to devote to it either, but I'll definitely keep fixing problems when our build breaks. :-)

**Comment by LionsAd** [comment]
@dsnopek Done, you are a collaborator now.

**Comment by mglaman** [comment]
Follow up for D8 environment in #78. This is breaking drupalcommerce/commerce tests (possibly.)

**Pull request merged**
