### PR TITLE
Support running tests based on 8.1.x.

### PR DESCRIPTION
**Pull request by slashrsm**
It seems that this is currently not possible.

### CODE REVIEW

**Comment by Berdir** [comment]
Yes please.

**Comment by Berdir** [comment]
By now, we might even want to make 8.1.x the default? d.o even defaults to 8.2.x now.

**Comment by slashrsm** [comment]
Yes! Updated default branch and rebased on top of master.

**Comment by Berdir** [comment]
See my referenced PR, this won't work without that, feel free to merge that into your PR and I'll close mine again

**Comment by slashrsm** [comment]
Done. #72 can be closed now.

**Comment by bojanz** [comment]
+1
This is blocking Commerce at the moment.

**Comment by Berdir** [comment]
For anyone waiting on this, note that you can reference the commit here directly, see https://github.com/drupalcommerce/commerce/pull/361#issuecomment-203093729 for more information.

**Comment by svendecabooter** [comment]
+1 - this works for me, and should be default behaviour.

**Comment by LionsAd** [comment]
Merged thanks. Created follow-up issue to document the parameter.

**Pull request merged**
